### ISSUE TITLE
qb-target

### ISSUE THREAD

**Issue by Glen92** [MaDHouSe79/mh-atmrobbery#4]
Hi,

My qb-target doesnt show up, and i see you use qb-atms in your scripts that isn't a thing anymore.

**Comment by Glen92** [comment]
![image](https://github.com/MaDHouSe79/mh-atmrobbery/assets/42032794/4b59145a-4cca-4fb1-bff6-80b2b109db4f)

**Comment by MaDHouSe79** [comment]
This script don't use `qb-atms` and you need a `weapon_stickybomb` in your inventory before it works.

**Comment by Glen92** [comment]
Heb ik in mijn invetory.
Zie onderstaande screenshot van je script.
![image](https://github.com/MaDHouSe79/mh-atmrobbery/assets/42032794/ed9ab5dd-16dc-4d07-9250-9ef596ce87a7)

**Comment by MaDHouSe79** [comment]
die overuled the normale qb-atm target omdat die anders weg valt, 
maar qb-atm heeft niet veel met dit script te maken dan alleen dit.

ook dit: https://github.com/MaDHouSe79/mh-atmrobbery/blob/c5fe076574618cb0d7c2e613e6fcd0de8aa45371/client/main.lua#L179
als je dit al hebt gedaan werkt het pas na een cooldown weer.
je kunt het script niet even herstarten je moet echt de server restarten.

**Comment by Glen92** [comment]
merk het inderdaad alleen nu zegt hij

![image](https://github.com/MaDHouSe79/mh-atmrobbery/assets/42032794/3d6c7464-bee0-4450-98ce-4ab163635c11)

terwijl mincops op 0 staat heb je daar een tip voor :)?

![image](https://github.com/MaDHouSe79/mh-atmrobbery/assets/42032794/ff0f2555-c6eb-4c1a-a64a-3f1eaa5bdc38)

**Comment by MaDHouSe79** [comment]
verander dit naar jou script
https://github.com/MaDHouSe79/mh-atmrobbery/blob/e1c2a4a5c1a058ddbe87bbe3d3befcfb5cabfc2e/client/main.lua#L299
het word van
```lua
if countCops > Config.MinCops then
```
naar 
```lua
if countCops >= Config.MinCops then
```

**Comment by Glen92** [comment]
topper dankje!

nu nog zorgen dat er een PS Dispatch alert in komt maar dat zal wel goed komen.

**Comment by MaDHouSe79** [comment]
ik ondersteun geen ps script meer, die gasten ondersteunen ook niets en niemand dus ik hun ook niet sorry man.

**Comment by Glen92** [comment]
geen probleem :) je hebt me al genoeg geholpen nogmaals bedankt!
